on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Build Image & Push DockerHub & Deploy EKS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Github에 저장된 코드를 CI 서버로 내려받아 뒷 step에서 사용할 수 있도록 하는 과정
      - name: Checkout
        uses: actions/checkout@v2

      # Github Secret과 local env 에 저장된 값 불러오기
      - name: Configure DockerHub Credentials
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - name: Build, tag, and push the image to DockerHub
        id: build-image
        env:
          DOCKERHUB_ID: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_REPOSITORY: daily-pt-ai
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t $DOCKERHUB_ID/$DOCKERHUB_REPOSITORY:$IMAGE_TAG .
          docker tag $DOCKERHUB_ID/$DOCKERHUB_REPOSITORY:$IMAGE_TAG $DOCKERHUB_ID/$DOCKERHUB_REPOSITORY:$IMAGE_TAG
          echo "Pushing image to DockerHub..."
          docker push $DOCKERHUB_ID/$DOCKERHUB_REPOSITORY:$IMAGE_TAG
      # kustomize 명령을 가져온다.
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout kustomize repository
        uses: actions/checkout@v2
        with:
          # kubernetes 설정정보 저장소
          repository: DailyPt/daily-pt-infra # k8s yaml 파일이 있는 repo
          ref: main # branch 이름
          # 다른 저장소에 push 하려면 Personal Access Token이 필요.
          token: ${{ secrets.ACTION_TOKEN }}
          path: daily-pt-infra # 최상위 경로로 repository와 동일하게 설정

      # 새 이미지 버전으로 파일 수정
      - name: Update Kubernetes object to new image
        env:
          DOCKERHUB_ID: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_REPOSITORY: daily-pt-ai
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          cd daily-pt-infra
          sed -i "s|image:.*|image: $DOCKERHUB_ID\/$DOCKERHUB_REPOSITORY:$IMAGE_TAG|g" daily-pt-ai-deployment.yaml
          cat daily-pt-ai-deployment.yaml
      # 수정된 파일 commit & push
      - name: Commit and push files
        env:
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          cd daily-pt-infra
          git config --global user.email "xman0120@naver.com"
          git config --global user.name "suhwan12"
          git commit -am "Update image tag $IMAGE_TAG"
          git push -u origin main
